name: Deploy React folder
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [12.x]
        steps:
        - name: Checkout del repositorio
          uses: actions/checkout@v2
    
        - name: Configurar Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 12
    
        - name: Instalar dependencias
          run: npm install
    
        - name: Compilar proyecto
          run: npm run build
