name: Despliegue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js 18.16.0
      uses: actions/setup-node@v2
      with:
        node-version: 18.16.0

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build
