name: Despliegue

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js 18.16.0
      uses: actions/setup-node@v3
      with:
        node-version: 18.16.0

    - name: Install dependencies
      run: npm install --production

    - name: Build
      run: npm run build

    - name: Position
      run: cd build

    - name: Eliminar contenido
      run: |
        if [ "$(ls -A /var/www/html)" ]; then
            sudo find /var/www/html -mindepth 1 ! -type d -exec rm {} \;
            sudo rm -r /var/www/html/static
        else
            echo "No hay archivos que eliminar"
        fi

    - name: Copy files
      run: sudo cp -r build/* /var/www/html
    
    - name: Actualiza nginx
      run: sudo service nginx restart