name: Deploy React folder
on:
    push:
        branches: ["main"]
jobs:
    build:
        runs-on: self-hosted
        strategy:
            matrix:
                node-version: [20.x]
        steps:
        - name: Instalar dependencias
          run: npm install
    
        - name: Compilar proyecto
          run: npm run build
